### ISSUE TITLE
Ey, ich lebe noch

### ISSUE THREAD

**Issue by nonchris** [t1z1an/Hydro#1]
Bezüglich Zeile 1... lol

Hydro for ever

**Comment by thisryan** [comment]
Sicher?

**Comment by nonchris** [comment]
Denke?

**Comment by thisryan** [comment]
Na dann der Hinweis: "noch"

**Comment by nonchris** [comment]
@thisryan was soll das denn jetzt heißen? :monocle_face:

**Comment by thisryan** [comment]
🙃

**Comment by nonchris** [comment]
:thinking:

**Comment by thisryan** [comment]
🔪

**Comment by nonchris** [comment]
Aber aber... doch nicht deinem eigenen Hydro Homie gegenüber so gemein sein :(

**Comment by thisryan** [comment]
💧

**Comment by nonchris** [comment]
:smiling_face_with_three_hearts: :droplet:

**Comment by thisryan** [comment]
❤️
